### ISSUE TITLE
Cool project but no hard to install

### ISSUE THREAD

**Issue by Kif11** [frankhale/toby#94]
I would be nice to have prebuilt apps for mac and win

**Comment by frankhale** [comment]
Yeah the install process is rough and currently a stumbling point. I'll see what I can do, I need to make a release which would ease the burden.

**Comment by frankhale** [comment]
This is about to be fixed. Currently can only do a build on Windows. Will release very soon.

**Comment by frankhale** [comment]
Release 1.0.1 should help alleviate the issues but I don't think the project will get any simpler to install from source due to all the moving parts. I quite like the architecture overall as it done in a sort of agnostic way allowing Toby to run in NW.js, Electron or regular browser. Unfortunately there are a lot of dependencies that have to be setup and the code has to be built when doing all this via source. Lots of potential problems could go wrong causing it not to run. 

https://github.com/frankhale/toby/releases/tag/v1.0.1

Unfortunately I cannot support Linux or Mac at this time but would be willing to take pull requests if there are issues running on these platforms.
